name: Build and Deploy AI Weather App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}  # Keep this as your Docker Hub username
        password: ${{ secrets.DOCKERHUB_TOKEN }}   

    - name: Create .env file
      run: |
        echo "OPEN_WEATHER_TOKEN=${{ secrets.OPEN_WEATHER_TOKEN }}" >> .env
        echo "REPLICATE_API_TOKEN=${{ secrets.REPLICATE_API_TOKEN }}" >> .env

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ai_weather_app:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/ai_weather_app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: SSH into EC2 and deploy
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ai_weather_app:latest
          docker stop ai_weather_app || true
          docker rm ai_weather_app || true
          docker run -d --name ai_weather_app -p 8000:8000 ${{ secrets.DOCKERHUB_USERNAME }}/ai_weather_app:latest
